- hosts: host1
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: absent



    - name: ensure apace2 is running
      service:
        name: apache2
        state: started
